### ISSUE TITLE
Apple Silicon Support?

### ISSUE THREAD

**Issue by patrickbryant** [esimov/triangle#27]
I have a project which uses [glumpy](https://github.com/glumpy/glumpy/issues/298) and am trying to get it running natively on my new MacBook. Is there any plan to compile this package for ARM? 

```
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:16) 
[Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import triangle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/patrickbryant/miniforge3/envs/py38/lib/python3.8/site-packages/triangle/__init__.py", line 13, in <module>
    from .tri import (
  File "/Users/patrickbryant/miniforge3/envs/py38/lib/python3.8/site-packages/triangle/tri.py", line 1, in <module>
    from .core import triang
ImportError: dlopen(/Users/patrickbryant/miniforge3/envs/py38/lib/python3.8/site-packages/triangle/core.cpython-38-darwin.so, 0x0002): tried: '/core.cpython-38-darwin.so' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib//core.cpython-38-darwin.so' (no such file), '/Users/patrickbryant/miniforge3/envs/py38/lib/python3.8/site-packages/triangle/core.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

**Comment by esimov** [comment]
Unfortunately I don't own an M1 to be able to test it.
